-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE IF NOT EXISTS CDT_COMPONENT(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_PROBLEM(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_SOLUTION(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_CLIENT(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_MODEL(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_EQUIPMENT(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_CLIENT INT NOT NULL REFERENCES CDT_CLIENT(ID),
  ID_MODEL INT NOT NULL REFERENCES CDT_MODEL(ID),
  SERIAL_NUMBER VARCHAR2(4000),
  DESCRIPTION VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_ORDER(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_EQUIPMENT INT NOT NULL REFERENCES CDT_EQUIPMENT(ID),
  NF_NUMBER VARCHAR2(4000),
  DT_TM_UTC_START TIMESTAMP NOT NULL,
  DT_TM_UTC_END TIMESTAMP NOT NULL,
  STATUS VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_ORDER_COMPONENT(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_ORDER INT NOT NULL REFERENCES CDT_ORDER(ID),
  ID_COMPONENT INT NOT NULL REFERENCES CDT_COMPONENT(ID)
);

CREATE TABLE IF NOT EXISTS CDT_ORDER_PROBLEM(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_ORDER INT NOT NULL REFERENCES CDT_ORDER(ID),
  ID_PROBLEM INT NOT NULL REFERENCES CDT_PROBLEM(ID)
);

CREATE TABLE IF NOT EXISTS CDT_ORDER_SOLUTION(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_ORDER INT NOT NULL REFERENCES CDT_ORDER(ID),
  ID_SOLUTION INT NOT NULL REFERENCES CDT_SOLUTION(ID)
);

CREATE TABLE IF NOT EXISTS CDT_USER(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR2(4000),
  PASSWORD VARCHAR2(4000),
  EMAIL VARCHAR2(4000),
  TIMEZONE VARCHAR2(4000),
  ACCESS_LEVEL VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_WORK_ORDER(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_ORDER INT NOT NULL REFERENCES CDT_ORDER(ID),
  ID_USER INT NOT NULL REFERENCES CDT_USER(ID),
  DT_TM_UTC_START TIMESTAMP NOT NULL,
  DT_TM_UTC_END TIMESTAMP NOT NULL,
  VL_TIME_IN_SECONDS INT,
  POSTSCRIPT VARCHAR2(4000)
);

CREATE TABLE IF NOT EXISTS CDT_ORDER_HISTORY(
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_ORDER INT NOT NULL REFERENCES CDT_ORDER(ID),
  ID_USER INT NOT NULL REFERENCES CDT_USER(ID),
  DT_TM_UTC TIMESTAMP NOT NULL,
  STATUS VARCHAR2(4000),
  POSTSCRIPT VARCHAR2(4000)
);